- name: configure DB
  hosts: db
  become: yes
  vars:
    login_host: 172.31.30.156
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable system services
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install mysql python dependencies
    ansible.builtin.pip:
      name:
      - pymySQL
      - cryptography
      executable: pip3.9  #pip3.11if python version is 3.11    

# check password is already is setup or not
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output  

  - name: print output
    ansible.builtin.debug:
      msg: "output {{mysql_connection_output}}"   

  