- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable ngix services
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      
        